version: '3'
services: 
  first:
    build:
      context: ./first
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - ./first:/app
    ports: 
      - "5000:5000"
  second:
    build:
      context: ./second
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - ./second:/app
    ports: 
      - "5001:5001"